"""add doc_type to deadlines

Revision ID: 3793ead81a32
Revises: c5fb11a25fa2
Create Date: 2026-04-17 01:28:52.315543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3793ead81a32'
down_revision: Union[str, Sequence[str], None] = 'c5fb11a25fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('doc_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadlines', 'doc_type')
    # ### end Alembic commands ###
