"""add supervisor requests, rejected advisors, resubmission count

Revision ID: 7f5ba72c7948
Revises: 3793ead81a32
Create Date: 2026-06-18 16:24:35.791404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5ba72c7948'
down_revision: Union[str, Sequence[str], None] = '3793ead81a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('rejected_advisor_ids', sa.Text(), nullable=True))
    op.add_column('proposals', sa.Column('resubmission_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'resubmission_count')
    op.drop_column('groups', 'rejected_advisor_ids')
    # ### end Alembic commands ###
